#!/bin/sh

stagedFiles=$(git diff --staged --name-only)

echo "Running spotlessApply. Formatting code..."
./gradlew spotlessApply --no-configuration-cache

for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done
