[versions]

kotlin = "1.7.20"

[libraries]

android-tools-gradle-plugin = "com.android.tools.build:gradle:7.3.0"

detekt-gradle-plugin = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.21.0"

kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

semver-gradle-plugin = "net.thauvin.erik.gradle:semver:1.0.4"

sonarqube-gradle-plugin = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.4.0.2513"
