import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val material_values: String = "blue.aodev:material-values:_"

    public const val espresso_core: String = "com.android.support.test.espresso:espresso-core:_"

    public const val com_android_support_test_runner: String = "com.android.support.test:runner:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    public const val fixture: String = "com.appmattus.fixture:fixture:_"

    public const val remotedata: String = "com.github.torresmi:remotedata:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val ktlint: String = "com.pinterest:ktlint:_"

    public const val moshi: String = "com.squareup.moshi:moshi:_"

    public const val converter_moshi: String = "com.squareup.retrofit2:converter-moshi:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val gradle_android_junit_jacoco_plugin: String =
            "com.vanniktech:gradle-android-junit-jacoco-plugin:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val arrow_core: String = "io.arrow-kt:arrow-core:_"

    public const val arrow_syntax: String = "io.arrow-kt:arrow-syntax:_"

    public const val coil: String = "io.coil-kt:coil:_"

    public const val kotlin_faker: String = "io.github.serpro69:kotlin-faker:_"

    public const val detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:_"

    public const val kotest_assertions_core: String = "io.kotest:kotest-assertions-core:_"

    public const val kotest_property: String = "io.kotest:kotest-property:_"

    public const val kotest_runner_junit5: String = "io.kotest:kotest-runner-junit5:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val org_jacoco_agent: String = "org.jacoco:org.jacoco.agent:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:_"

    public const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:_"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    public const val ktlint_gradle: String = "org.jlleitschuh.gradle:ktlint-gradle:_"

    public const val koin_android: String = "org.koin:koin-android:_"

    public const val koin_test: String = "org.koin:koin-test:_"
}
