name: Dependency Updates

on:
  workflow_run:
    workflows: ["Pull Request Auto Update With Target"]
    types:
      - completed
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Refresh versions
        uses: burrunan/gradle-cache-action@v1
        with:
          gradle-dependencies-cache-key: |
            buildSrc/**/Libs.kt
          arguments: |
            refreshVersions --no-configuration-cache

      - name: PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_TRIGGER_TOKEN }}
          commit-message: refresh dependency updates
          branch: dependency-updates
          title: New Dependency Updates Available
          body: |
            * Updates versions file with new dependency updates available
          labels: |
            dependencies
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          assignees: torresmi
