name: Publish mkdocs via GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - mkdocs.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.x
      
      - name: Deploy Docs
        run: |
          pip install mkdocs-material 
          mkdocs gh-deploy --force
