name: Pull Request Merge Command

on: issue_comment

jobs:
  merge-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Merge command
      uses: Goobles/gh-actions-merge-command@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
