name: Pull Request Auto Update With Target

on:
  push: {}

jobs:
  auto-update:
   name: auto-update
   runs-on: ubuntu-latest
   steps:
    - uses: docker://chinthakagodawita/autoupdate-action:v1
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TRIGGER_TOKEN  }}
