name: Pull Request Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:

  # Automatically assign labels based on code content
  label_content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
