name: Pull Request Labeler

on:
  workflow_run:
    workflows: ["Pull Request Auto Update With Target"]
    types:
      - completed
  pull_request:

jobs:
  label_content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
